### ISSUE TITLE
Archive this repo

### ISSUE THREAD

**Issue by tomasholderness** [urbanriskmap/cognicity-lambda#5]
@matthewberryman just wanted to confirm with you that we can archive this repo.

Proposal is to move it to MIT Github for reference as per https://github.com/orgs/urbanriskmap/projects/1#card-4891443

**Comment by matthewberryman** [comment]
Confirm it can be archived. I have made a copy at MIT GH. Closing but will leave this repo around until you've read this message @talltom (delete when you get this).
